apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.db.name }}
            - name: MYSQL_USER
              value: {{ .Values.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.db.password }}
