replicaCount: 1
image:
  repository: bitnami/wordpress
  tag: 5.8.1-debian-10-r0
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
wordpressUsername: admin
wordpressPassword: mysecretpassword
