apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_USERNAME
              value: {{ .Values.wordpressUsername }}
            - name: WORDPRESS_PASSWORD
              value: {{ .Values.wordpressPassword }}
