apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
