apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer   # Change service type to LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: wordpress
  healthCheckNodePort: 80  # Define the health check port
